// src/app/p/test/page.tsx
// Auto-generated by CMS on 2026-03-08
// Page: "Test" (id: test)
// Edit content in the CMS admin panel — this file only needs to exist.

export { default, generateStaticParams } from '@/app/p/[slug]/page';
export { dynamic } from '@/app/p/[slug]/page';
