// src/app/api/admin/github-page/route.ts
// Writes / deletes real Next.js page files directly in the GitHub repo.
// Each landing page becomes src/app/p/<slug>/page.tsx with the page ID hardcoded.
// Vercel detects the push and rebuilds automatically (~60s).

import { NextRequest, NextResponse } from 'next/server';
import { getAdminSession } from '@/lib/admin-auth';
import { supabase } from '@/lib/supabase';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const GITHUB_TOKEN  = process.env.GITHUB_TOKEN!;
const GITHUB_REPO   = process.env.GITHUB_REPO!;
const GITHUB_BRANCH = process.env.GITHUB_BRANCH || 'main';

// ─── GitHub API helpers ───────────────────────────────────────────────────────

async function ghGet(path: string) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${path}?ref=${GITHUB_BRANCH}`, {
    headers: { Authorization: `token ${GITHUB_TOKEN}`, Accept: 'application/vnd.github.v3+json' },
    cache: 'no-store',
  });
  return res.ok ? res.json() : null;
}

async function ghPut(filePath: string, message: string, fileContent: string, sha?: string) {
  const body: Record<string, string> = {
    message,
    content: Buffer.from(fileContent, 'utf-8').toString('base64'),
    branch: GITHUB_BRANCH,
  };
  if (sha) body.sha = sha;
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${filePath}`, {
    method: 'PUT',
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json.message || 'GitHub PUT failed');
  return json;
}

async function ghDelete(filePath: string, message: string, sha: string) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${filePath}`, {
    method: 'DELETE',
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ message, sha, branch: GITHUB_BRANCH }),
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json.message || 'GitHub DELETE failed');
  return json;
}

// ─── Page template — standalone, page ID hardcoded ───────────────────────────
// This is a complete, self-contained Next.js page. The page ID is baked in
// so there is zero lookup logic — it always loads the right content.

function generatePageFile(pageId: string, label: string): string {
  return `// Auto-generated by CMS — ${new Date().toISOString().split('T')[0]}
// Page: "${label}" · id: ${pageId}
// Edit content in the Admin CMS panel. Do not rename this file.

import type { CSSProperties } from "react";
import Footer from "@/components/ui/Footer";
import TopHeader from "@/components/TopHeader";
import Image from "next/image";
import { Button } from "@/components/ui/Button";
import Quiz from "@/components/quiz";
import { VideoCarousel, TestimonialVideos } from "@/app/components/VideoSection";
import { supabase } from "@/lib/supabase";
import { Award, Check, GraduationCap, ShieldCheck, Star, Trophy, Users, Video, MicVocal } from "lucide-react";

export const dynamic = "force-dynamic";

const PAGE_ID = "${pageId}";
const sectionWidth = "mx-auto w-full max-w-[1200px] px-4 md:px-6";

type Sec = { section_instance: string; section_type: string; hidden: boolean; sort_order: number };

async function load() {
  const [cmsR, sectR, headerR, globalR] = await Promise.all([
    supabase.from("cms_content").select("section_key,field_key,value").eq("page", PAGE_ID),
    supabase.from("cms_sections").select("section_instance,section_type,hidden,sort_order").eq("page_id", PAGE_ID).order("sort_order"),
    supabase.from("cms_content").select("section_key,field_key,value").eq("page", "component_header"),
    supabase.from("global_settings").select("*"),
  ]);
  const cms: Record<string,string> = {};
  for (const e of cmsR.data || []) cms[\`\${e.section_key}::\${e.field_key}\`] = e.value;
  const headerCms: Record<string,string> = {};
  for (const e of headerR.data || []) headerCms[\`\${e.section_key}::\${e.field_key}\`] = e.value;
  const global: Record<string,string> = {};
  for (const e of globalR.data || []) global[e.key] = e.value;
  return { cms, sections: (sectR.data || []) as Sec[], headerCms, global };
}

function CmsImage({ src, alt, fill, width, height, className, priority }: { src:string; alt:string; fill?:boolean; width?:number; height?:number; className?:string; priority?:boolean }) {
  if (!src) return null;
  if (src.startsWith("http")) {
    if (fill) return <img src={src} alt={alt} className={\`absolute inset-0 h-full w-full \${className||""}\`} style={{objectFit:"cover"}} />;
    return <img src={src} alt={alt} width={width} height={height} className={className} />;
  }
  if (fill) return <Image src={src} alt={alt} fill className={className} priority={priority} />;
  return <Image src={src} alt={alt} width={width||400} height={height||300} className={className} />;
}

function RT({ text, className }: { text:string; className?:string }) {
  if (!text) return null;
  const parts = text.split(/(\\*\\*[^*]+\\*\\*|\\*[^*]+\\*)/g);
  return <span className={className}>{parts.map((p,i) => p.startsWith("**")&&p.endsWith("**") ? <strong key={i}>{p.slice(2,-2)}</strong> : p.startsWith("*")&&p.endsWith("*") ? <em key={i}>{p.slice(1,-1)}</em> : p)}</span>;
}

export default async function Page() {
  const { cms, sections, headerCms, global } = await load();
  const c  = (k:string) => cms[k] ?? "";
  const ci = (inst:string, f:string) => cms[\`\${inst}::\${f}\`] ?? "";

  const showHeader = cms["layout::show_header"] !== "false";
  const showFooter = cms["layout::show_footer"] !== "false";

  const headerLogoText   = headerCms["header::logo_text"]   || "MARTIN KRENDL";
  const headerCtaLabel   = headerCms["header::cta_label"]   || "Kostenloses Kennenlernen";
  const headerCtaLink    = headerCms["header::cta_link"]    || "#quiz";
  const headerBg         = headerCms["header::bg_color"]    || "#884A4A";
  const headerShowTopbar = headerCms["header::show_topbar"] !== "false";
  const headerTopbarText = headerCms["header::topbar_text"] || "Gesangsunterricht in Steyr oder online 🎶";
  const headerTopbarBg   = headerCms["header::topbar_bg"]   || "#e0e0e0";
  const headerTopbarColor = headerCms["header::topbar_color"] || "#333333";

  const fontFamily = global["font_family"] || "Open Sans";
  const fontUrl    = global["font_url"]    || \`https://fonts.googleapis.com/css2?family=\${encodeURIComponent(fontFamily)}:wght@400;600;700;800&display=swap\`;

  const brand     = c("colors::brand")      || "#884A4A";
  const graphite  = c("colors::graphite")   || "#2F2F2F";
  const darkGray  = c("colors::dark_gray")  || "#4A4A4A";
  const lightGray = c("colors::light_gray") || "#6B6B6B";
  const quizBg    = c("colors::quiz_bg")    || "#F7F7F7";

  const active = sections.filter(s => !s.hidden);

  const render: Record<string,(inst:string)=>React.ReactNode> = {
    header: () => null,
    global_colors: () => null,
    hero: (inst) => {
      const img = ci(inst,"image") || "/martin-desktop.jpg";
      return (
        <section key={inst} className="relative">
          <div className="relative aspect-square w-full md:aspect-[16/6]">
            <CmsImage src={img} alt="Hero" fill className="object-cover" priority />
            <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-black/10" />
            <div className="absolute inset-x-0 bottom-0">
              <div className={\`\${sectionWidth} pb-10 md:pb-14\`}>
                <div className="mx-auto max-w-4xl text-center text-white">
                  <h1 className="text-3xl font-extrabold leading-tight md:text-5xl"><RT text={ci(inst,"title")||"Sing freier, sicherer und mit mehr Ausdruck"} /></h1>
                  {ci(inst,"subtitle")&&<p className="mt-4 text-sm text-white/85 md:text-lg"><RT text={ci(inst,"subtitle")} /></p>}
                  <div className="mt-6"><a href={ci(inst,"cta_link")||"#quiz"}><Button className="rounded-[4px] px-6 py-3 font-semibold text-white" style={{backgroundColor:brand}}>{ci(inst,"cta_label")||"Probestunde anfragen"}</Button></a></div>
                  {ci(inst,"social_proof")&&<div className="mt-4 flex flex-col items-center gap-2"><div className="flex gap-1">{Array.from({length:5}).map((_,i)=><Star key={i} className="h-5 w-5 fill-[#D4AF37] text-[#D4AF37]"/>)}</div><p className="text-sm font-semibold text-white/90">{ci(inst,"social_proof")}</p></div>}
                </div>
              </div>
            </div>
          </div>
        </section>
      );
    },
    hero_legacy: (inst) => render["hero"](inst),
    flowing_text: (inst) => (
      <section key={inst} className="py-16 md:py-20" style={{backgroundColor:brand}}>
        <div className={sectionWidth}><p className="mx-auto max-w-4xl text-center text-xl font-semibold leading-9 text-white md:text-2xl md:leading-10"><RT text={ci(inst,"text")||c("flowing_text::text")} /></p></div>
      </section>
    ),
    flowing_text_legacy: (inst) => render["flowing_text"](inst),
    quote: (inst) => {
      const bg = ci(inst,"bg")||c("images::quote_bg");
      return (
        <section key={inst} className="relative py-20 md:py-28">
          {bg&&<CmsImage src={bg} alt="" fill className="object-cover"/>}
          <div className="absolute inset-0 bg-black/60"/>
          <div className={\`\${sectionWidth} relative\`}><div className="mx-auto max-w-3xl text-center">
            {(ci(inst,"label")||c("quote_section::label"))&&<p className="mb-4 text-sm font-semibold uppercase tracking-widest text-white/70">{ci(inst,"label")||c("quote_section::label")}</p>}
            <blockquote className="text-2xl font-bold italic leading-10 text-white md:text-3xl"><RT text={ci(inst,"quote")||c("quote_section::quote")} /></blockquote>
          </div></div>
        </section>
      );
    },
    quote_legacy: (inst) => render["quote"](inst),
    final_cta: (inst) => {
      const img = ci(inst,"image")||c("images::final_cta");
      return (
        <section key={inst} className="relative py-20 md:py-28">
          {img&&<CmsImage src={img} alt="" fill className="object-cover"/>}
          <div className="absolute inset-0 bg-black/60"/>
          <div className={\`\${sectionWidth} relative\`}><div className="mx-auto max-w-2xl text-center text-white">
            <h2 className="text-3xl font-extrabold md:text-4xl"><RT text={ci(inst,"title")||c("final_cta::title")} /></h2>
            {(ci(inst,"text")||c("final_cta::text"))&&<p className="mt-5 text-lg leading-8 text-white/85"><RT text={ci(inst,"text")||c("final_cta::text")} /></p>}
            <a href={ci(inst,"cta_link")||c("links::final_cta")||"#quiz"} className="mt-8 inline-block rounded-[4px] px-8 py-4 font-bold text-white hover:opacity-95" style={{backgroundColor:brand}}>{ci(inst,"cta_label")||c("final_cta::cta_label")}</a>
          </div></div>
        </section>
      );
    },
    final_cta_legacy: (inst) => render["final_cta"](inst),
    quiz: (inst) => (
      <section key={inst} id="quiz" className="py-16 md:py-20" style={{backgroundColor:quizBg}}>
        <div className={sectionWidth}><Quiz quizId={ci(inst,"quiz_id")||"component_quiz"} /></div>
      </section>
    ),
    image_text: (inst) => {
      const bullets = [ci(inst,"bullet_1"),ci(inst,"bullet_2"),ci(inst,"bullet_3")].filter(Boolean);
      return (
        <section key={inst} className="py-16 md:py-20">
          <div className={sectionWidth}><div className="grid gap-12 md:grid-cols-2 md:items-center">
            {ci(inst,"image")&&<div className="relative aspect-square overflow-hidden rounded-[4px]"><CmsImage src={ci(inst,"image")} alt="" fill className="object-cover"/></div>}
            <div>
              {ci(inst,"title")&&<h2 className="text-3xl font-extrabold md:text-4xl" style={{color:graphite}}><RT text={ci(inst,"title")} /></h2>}
              {ci(inst,"text")&&<p className="mt-5 text-base leading-8" style={{color:darkGray}}><RT text={ci(inst,"text")} /></p>}
              {bullets.length>0&&<ul className="mt-6 space-y-3">{bullets.map((b,i)=><li key={i} className="flex items-start gap-3"><Check className="mt-0.5 h-5 w-5 shrink-0" style={{color:brand}}/><span className="text-base" style={{color:darkGray}}><RT text={b}/></span></li>)}</ul>}
              {ci(inst,"cta_label")&&<a href={ci(inst,"cta_link")||"#quiz"} className="mt-8 inline-block rounded-[4px] px-7 py-3.5 font-semibold text-white hover:opacity-95" style={{backgroundColor:brand}}>{ci(inst,"cta_label")}</a>}
            </div>
          </div></div>
        </section>
      );
    },
    image_text_1: (inst) => render["image_text"](inst),
    image_text_2: (inst) => render["image_text"](inst),
    logos: (inst) => {
      const logos = [ci(inst,"logo_1")||c("images::logo1"), ci(inst,"logo_2")||c("images::logo2"), ci(inst,"logo_3")||c("images::logo3")].filter(Boolean);
      return (
        <section key={inst} className="py-12 md:py-14"><div className={sectionWidth}>
          {(ci(inst,"label")||c("logos_section::label"))&&<div className="mx-auto mb-8 max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em]" style={{color:brand}}>{ci(inst,"label")||c("logos_section::label")}</p></div>}
          <div className="flex flex-wrap items-center justify-center gap-4 md:gap-6">{logos.map((logo,i)=><div key={i} className="flex h-28 w-[min(100%,260px)] items-center justify-center rounded-[4px] border border-neutral-200 bg-white p-4 md:h-32"><CmsImage src={logo} alt={\`Logo \${i+1}\`} width={180} height={80} className="max-h-14 w-auto object-contain md:max-h-16"/></div>)}</div>
        </div></section>
      );
    },
    logos_legacy: (inst) => render["logos"](inst),
    feature_cards_3: (inst) => {
      const cards=[1,2,3].map(n=>({title:ci(inst+n,"title")||c(\`feature_card_\${n}::title\`),text:ci(inst+n,"text")||c(\`feature_card_\${n}::text\`)}));
      const icons=[GraduationCap,Trophy,ShieldCheck];
      return (
        <section key={inst} className="pt-8 pb-14 md:pt-10 md:pb-20"><div className={sectionWidth}><div className="grid gap-4 md:grid-cols-3 md:gap-6">{cards.map((card,i)=>{const Icon=icons[i];return(<div key={i} className="rounded-[4px] px-6 py-8 text-center text-white" style={{backgroundColor:brand}}><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-[4px] border border-white/20 bg-white/10"><Icon className="h-7 w-7 text-white"/></div><h3 className="text-xl font-bold"><RT text={card.title}/></h3><p className="mt-3 text-sm leading-7 text-white/90"><RT text={card.text}/></p></div>);})}</div></div></section>
      );
    },
    feature_cards_3_legacy: (inst) => render["feature_cards_3"](inst),
    feature_cards_4: (inst) => {
      const heading=ci(inst+"h","title")||c("features_2_heading::title");
      const subtext=ci(inst+"h","text")||c("features_2_heading::text");
      const cards=[1,2,3,4].map(n=>({title:ci(inst+n,"title")||c(\`feature2_card_\${n}::title\`),text:ci(inst+n,"text")||c(\`feature2_card_\${n}::text\`)}));
      const icons=[Users,Award,Video,MicVocal];
      return (
        <section key={inst} className="py-14 md:py-20"><div className={sectionWidth}>
          {heading&&<div className="mx-auto mb-10 max-w-3xl text-center"><h2 className="text-3xl font-extrabold md:text-4xl"><RT text={heading}/></h2>{subtext&&<p className="mt-4" style={{color:lightGray}}><RT text={subtext}/></p>}</div>}
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4 md:gap-6">{cards.map((card,i)=>{const Icon=icons[i];return(<div key={i} className="rounded-[4px] px-5 py-7 text-center text-white" style={{backgroundColor:brand}}><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-[4px] border border-white/20 bg-white/10"><Icon className="h-7 w-7 text-white"/></div><h3 className="text-lg font-bold"><RT text={card.title}/></h3><p className="mt-3 text-sm leading-7 text-white/90"><RT text={card.text}/></p></div>);})}</div>
          <div className="mt-8 text-center"><a href={c("links::features_2_cta")||"#quiz"}><Button className="rounded-[4px] px-6 py-3 font-semibold text-white hover:opacity-95" style={{backgroundColor:brand}}>Zum Kennenlern-Quiz</Button></a></div>
        </div></section>
      );
    },
    feature_cards_4_legacy: (inst) => render["feature_cards_4"](inst),
    video_carousel: (inst) => {
      const videos=[{src:ci(inst,"vid1")||c("videos::carousel_1_src"),thumbnail:ci(inst,"thumb1")||c("videos::carousel_1_thumb")},{src:ci(inst,"vid2")||c("videos::carousel_2_src"),thumbnail:ci(inst,"thumb2")||c("videos::carousel_2_thumb")},{src:ci(inst,"vid3")||c("videos::carousel_3_src"),thumbnail:ci(inst,"thumb3")||c("videos::carousel_3_thumb")}].filter(v=>v.src);
      return <VideoCarousel key={inst} title={ci(inst,"title")||c("video_section::title")} text={ci(inst,"text")||c("video_section::text")} brandColor={brand} videos={videos}/>;
    },
    video_carousel_legacy: (inst) => render["video_carousel"](inst),
    testimonials: (inst) => {
      const t=(n:number,f:string)=>ci(\`\${inst}\${n}\`,f)||c(\`testimonial_\${n}::\${f}\`);
      const tv=(n:number,f:string)=>ci(\`\${inst}\${n}\`,f)||c(\`videos::testimonial_\${n}_\${f}\`);
      return <TestimonialVideos key={inst} t1label={t(1,"label")} t1quote={t(1,"quote")} t1author={t(1,"author")} t1src={tv(1,"src")} t1thumb={tv(1,"thumb")} t2label={t(2,"label")} t2quote={t(2,"quote")} t2author={t(2,"author")} t2src={tv(2,"src")} t2thumb={tv(2,"thumb")} brandColor={brand}/>;
    },
    testimonials_legacy: (inst) => render["testimonials"](inst),
    reviews: (inst) => {
      const title=ci(inst,"title")||c("reviews::title");
      const list=[1,2,3].map(n=>({text:ci(\`\${inst}\${n}\`,"text")||c(\`review_\${n}::text\`),author:ci(\`\${inst}\${n}\`,"author")||c(\`review_\${n}::author\`)})).filter(r=>r.text);
      return (
        <section key={inst} className="py-14 md:py-20"><div className={sectionWidth}>
          {title&&<div className="mx-auto mb-10 max-w-2xl text-center"><h2 className="text-3xl font-extrabold md:text-4xl"><RT text={title}/></h2></div>}
          <div className="overflow-x-auto pb-4 [scrollbar-width:none] md:overflow-visible"><div className="flex gap-4 md:grid md:grid-cols-3 md:gap-6">{list.map((r,i)=><div key={i} className="min-w-[88%] rounded-[4px] bg-neutral-100 p-6 md:min-w-0"><div className="mb-4 flex gap-1">{Array.from({length:5}).map((_,j)=><Star key={j} className="h-4 w-4 fill-[#D4AF37] text-[#D4AF37]"/>)}</div><p className="text-sm leading-7" style={{color:graphite}}><RT text={r.text}/></p><p className="mt-4 text-sm font-semibold" style={{color:brand}}>– {r.author}</p></div>)}</div></div>
        </div></section>
      );
    },
    reviews_legacy: (inst) => render["reviews"](inst),
    about: (inst) => {
      const img=ci(inst,"image")||c("images::about");
      return (
        <section key={inst} className="py-16 md:py-20"><div className={sectionWidth}><div className="grid gap-12 md:grid-cols-2 md:items-center">
          {img&&<div className="relative aspect-square max-w-sm overflow-hidden rounded-full mx-auto md:mx-0"><CmsImage src={img} alt="" fill className="object-cover"/></div>}
          <div>
            {(ci(inst,"label")||c("about::label"))&&<p className="mb-4 text-sm font-semibold uppercase tracking-widest" style={{color:brand}}>{ci(inst,"label")||c("about::label")}</p>}
            <h2 className="text-3xl font-extrabold md:text-4xl" style={{color:graphite}}><RT text={ci(inst,"title")||c("about::title")}/></h2>
            {[ci(inst,"text_1")||c("about::text_1"),ci(inst,"text_2")||c("about::text_2"),ci(inst,"text_3")||c("about::text_3")].filter(Boolean).map((t,i)=><p key={i} className="mt-4 text-base leading-8" style={{color:darkGray}}><RT text={t}/></p>)}
          </div>
        </div></div></section>
      );
    },
    about_legacy: (inst) => render["about"](inst),
  };

  const sections_rendered = active.map(s => { const fn=render[s.section_type]; return fn?fn(s.section_instance):null; }).filter(Boolean);

  return (
    <main className="min-h-screen bg-white" style={{"--brand":brand,"--graphite":graphite,"--darkGray":darkGray,"--lightGray":lightGray,"--quizBg":quizBg} as CSSProperties}>
      <style>{\`@import url('\${fontUrl}'); html{scroll-behavior:smooth;} body{font-family:'\${fontFamily}',sans-serif;color:var(--graphite);background:#ffffff;}\`}</style>
      {showHeader&&headerShowTopbar&&<TopHeader text={headerTopbarText} bgColor={headerTopbarBg} textColor={headerTopbarColor}/>}
      {showHeader&&(
        <header className="sticky top-0 z-50 border-b border-white/10" style={{backgroundColor:headerBg}}>
          <div className={\`\${sectionWidth} flex h-20 items-center justify-between\`}>
            <div className="text-left text-lg font-extrabold tracking-[0.18em] text-white md:text-xl">{headerLogoText}</div>
            <a href={headerCtaLink}><Button variant="secondary" className="rounded-[4px] px-6 py-3 font-semibold text-white">{headerCtaLabel}</Button></a>
          </div>
        </header>
      )}
      {sections_rendered as React.ReactNode[]}
      {showFooter&&<Footer/>}
    </main>
  );
}
`;
}

// ─── POST: create page ────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const session = await getAdminSession();
  if (!session) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  if (!GITHUB_TOKEN || !GITHUB_REPO) return NextResponse.json({ error: 'GITHUB_TOKEN und GITHUB_REPO env vars fehlen' }, { status: 500 });

  const body = await req.json().catch(() => ({}));
  const { label, slug, source_page } = body;
  if (!label || !slug) return NextResponse.json({ error: 'label und slug erforderlich' }, { status: 400 });

  const cleanSlug = slug.replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  const pageId    = cleanSlug;
  const path      = `/p/${cleanSlug}`;
  const filePath  = `src/app/p/${cleanSlug}/page.tsx`;

  // Check for duplicate
  const { data: existing } = await supabase.from('cms_pages').select('id').eq('id', pageId).maybeSingle();
  if (existing) return NextResponse.json({ error: `Seite "${cleanSlug}" existiert bereits` }, { status: 409 });

  // 1. Register in Supabase
  const { data: newPage, error: pageError } = await supabase
    .from('cms_pages').insert({ id: pageId, label, path, is_system: false }).select().single();
  if (pageError) return NextResponse.json({ error: pageError.message }, { status: 500 });

  // 2. Copy sections + content from source if duplicating
  if (source_page) {
    const { data: sourceSections } = await supabase
      .from('cms_sections').select('*').eq('page_id', source_page).order('sort_order');
    const instanceMap: Record<string, string> = {};
    if (sourceSections?.length) {
      const newSections = sourceSections.map((s, idx) => {
        const ts  = (Date.now() + idx).toString(36);
        const rnd = Math.random().toString(36).slice(2, 6);
        const newInst = `${s.section_type}_${ts}_${rnd}`;
        instanceMap[s.section_instance] = newInst;
        return { page_id: pageId, section_instance: newInst, section_type: s.section_type, label: s.label, sort_order: s.sort_order, hidden: s.hidden };
      });
      await supabase.from('cms_sections').insert(newSections);
    }
    const { data: srcContent } = await supabase.from('cms_content').select('*').eq('page', source_page);
    if (srcContent?.length) {
      await supabase.from('cms_content').insert(
        srcContent.map(c => ({ page: pageId, section_key: instanceMap[c.section_key] ?? c.section_key, field_key: c.field_key, value: c.value, updated_at: new Date().toISOString() }))
      );
    }
  }

  // 3. Write file to GitHub
  try {
    await ghPut(filePath, `CMS: Neue Seite "${label}" (${cleanSlug})`, generatePageFile(pageId, label));
  } catch (err: any) {
    // Rollback Supabase on GitHub failure
    await supabase.from('cms_content').delete().eq('page', pageId);
    await supabase.from('cms_sections').delete().eq('page_id', pageId);
    await supabase.from('cms_pages').delete().eq('id', pageId);
    return NextResponse.json({ error: `GitHub Fehler: ${err.message}` }, { status: 500 });
  }

  return NextResponse.json({ ok: true, data: newPage, path });
}

// ─── DELETE: remove page ──────────────────────────────────────────────────────

export async function DELETE(req: NextRequest) {
  const session = await getAdminSession();
  if (!session) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  if (!GITHUB_TOKEN || !GITHUB_REPO) return NextResponse.json({ error: 'GITHUB_TOKEN und GITHUB_REPO env vars fehlen' }, { status: 500 });

  const { id } = await req.json().catch(() => ({}));
  if (!id) return NextResponse.json({ error: 'id erforderlich' }, { status: 400 });

  const { data: page } = await supabase.from('cms_pages').select('*').eq('id', id).single();
  if (!page) return NextResponse.json({ error: 'nicht gefunden' }, { status: 404 });
  if (page.is_system) return NextResponse.json({ error: 'Systemseiten können nicht gelöscht werden' }, { status: 403 });

  // 1. Delete from GitHub
  const filePath = `src/app/p/${id}/page.tsx`;
  const existing = await ghGet(filePath);
  if (existing?.sha) {
    try {
      await ghDelete(filePath, `CMS: Seite "${page.label}" gelöscht`, existing.sha);
    } catch (err: any) {
      return NextResponse.json({ error: `GitHub Fehler: ${err.message}` }, { status: 500 });
    }
  }

  // 2. Clean Supabase
  await Promise.all([
    supabase.from('cms_content').delete().eq('page', id),
    supabase.from('cms_sections').delete().eq('page_id', id),
  ]);
  await supabase.from('cms_pages').delete().eq('id', id);

  return NextResponse.json({ ok: true });
}
