// src/app/api/admin/github-page/route.ts
// Writes / deletes real Next.js page files in the GitHub repo.
// Each new landing page becomes its own `src/app/p/<slug>/page.tsx`.
// Vercel detects the push and rebuilds automatically (~60s).

import { NextRequest, NextResponse } from 'next/server';
import { getAdminSession } from '@/lib/admin-auth';
import { supabase } from '@/lib/supabase';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN!;
const GITHUB_REPO  = process.env.GITHUB_REPO!;   // e.g. "username/martinkrendl"
const GITHUB_BRANCH = process.env.GITHUB_BRANCH || 'main';

// ─── GitHub API helpers ───────────────────────────────────────────────────────

async function ghGet(path: string) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/${path}`, {
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
    },
  });
  return res.ok ? res.json() : null;
}

async function ghPut(path: string, message: string, content: string, sha?: string) {
  const body: Record<string, string> = {
    message,
    content: Buffer.from(content).toString('base64'),
    branch: GITHUB_BRANCH,
  };
  if (sha) body.sha = sha;

  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${path}`, {
    method: 'PUT',
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json.message || 'GitHub PUT failed');
  return json;
}

async function ghDelete(path: string, message: string, sha: string) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${path}`, {
    method: 'DELETE',
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ message, sha, branch: GITHUB_BRANCH }),
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json.message || 'GitHub DELETE failed');
  return json;
}

// ─── Page template generator ─────────────────────────────────────────────────

function generatePageTemplate(pageId: string, slug: string, label: string): string {
  return `// src/app/p/${slug}/page.tsx
// Auto-generated by CMS on ${new Date().toISOString().split('T')[0]}
// Page: "${label}" (id: ${pageId})
// Edit content in the CMS admin panel — this file only needs to exist.

export { default, generateStaticParams } from '@/app/p/[slug]/page';
export { dynamic } from '@/app/p/[slug]/page';
`;
}

// ─── POST: create page file ───────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const session = await getAdminSession();
  if (!session) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });

  if (!GITHUB_TOKEN || !GITHUB_REPO) {
    return NextResponse.json({ error: 'GITHUB_TOKEN and GITHUB_REPO env vars required' }, { status: 500 });
  }

  const body = await req.json().catch(() => ({}));
  const { label, slug, source_page } = body;
  if (!label || !slug) return NextResponse.json({ error: 'label and slug required' }, { status: 400 });

  const cleanSlug = slug.replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  const pageId = cleanSlug;
  const path = `/p/${cleanSlug}`;
  const filePath = `src/app/p/${cleanSlug}/page.tsx`;

  // 1. Register in Supabase (for CMS content storage)
  const { data: existingPage } = await supabase
    .from('cms_pages').select('id').eq('id', pageId).maybeSingle();

  if (existingPage) {
    return NextResponse.json({ error: `Seite "${cleanSlug}" existiert bereits` }, { status: 409 });
  }

  const { data: newPage, error: pageError } = await supabase
    .from('cms_pages')
    .insert({ id: pageId, label, path, is_system: false })
    .select().single();
  if (pageError) return NextResponse.json({ error: pageError.message }, { status: 500 });

  // 2. If duplicating, copy sections + content from source
  if (source_page) {
    const { data: sourceSections } = await supabase
      .from('cms_sections').select('*').eq('page_id', source_page).order('sort_order');

    const instanceMap: Record<string, string> = {};
    if (sourceSections?.length) {
      const newSections = sourceSections.map((s, idx) => {
        const uniqueTs = (Date.now() + idx).toString(36);
        const rand = Math.random().toString(36).slice(2, 6);
        const newInstance = `${s.section_type}_${uniqueTs}_${rand}`;
        instanceMap[s.section_instance] = newInstance;
        return { page_id: pageId, section_instance: newInstance, section_type: s.section_type, label: s.label, sort_order: s.sort_order, hidden: s.hidden };
      });
      await supabase.from('cms_sections').insert(newSections);
    }
    const { data: sourceContent } = await supabase.from('cms_content').select('*').eq('page', source_page);
    if (sourceContent?.length) {
      await supabase.from('cms_content').insert(
        sourceContent.map(c => ({
          page: pageId,
          section_key: instanceMap[c.section_key] ?? c.section_key,
          field_key: c.field_key, value: c.value,
          updated_at: new Date().toISOString(),
        }))
      );
    }
  }

  // 3. Write the actual file to GitHub
  try {
    const content = generatePageTemplate(pageId, cleanSlug, label);
    await ghPut(filePath, `CMS: Neue Seite "${label}" (${cleanSlug})`, content);
  } catch (err: any) {
    // GitHub write failed — rollback Supabase
    await supabase.from('cms_content').delete().eq('page', pageId);
    await supabase.from('cms_sections').delete().eq('page_id', pageId);
    await supabase.from('cms_pages').delete().eq('id', pageId);
    return NextResponse.json({ error: `GitHub Fehler: ${err.message}` }, { status: 500 });
  }

  return NextResponse.json({ ok: true, data: newPage, path });
}

// ─── DELETE: remove page file ─────────────────────────────────────────────────

export async function DELETE(req: NextRequest) {
  const session = await getAdminSession();
  if (!session) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });

  if (!GITHUB_TOKEN || !GITHUB_REPO) {
    return NextResponse.json({ error: 'GITHUB_TOKEN and GITHUB_REPO env vars required' }, { status: 500 });
  }

  const { id } = await req.json().catch(() => ({}));
  if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 });

  const { data: page } = await supabase.from('cms_pages').select('*').eq('id', id).single();
  if (!page) return NextResponse.json({ error: 'not found' }, { status: 404 });
  if (page.is_system) return NextResponse.json({ error: 'cannot delete system page' }, { status: 403 });

  // 1. Delete file from GitHub first
  const filePath = `src/app/p/${id}/page.tsx`;
  const existing = await ghGet(`contents/${filePath}?ref=${GITHUB_BRANCH}`);
  if (existing?.sha) {
    try {
      await ghDelete(filePath, `CMS: Seite "${page.label}" gelöscht`, existing.sha);
    } catch (err: any) {
      return NextResponse.json({ error: `GitHub Fehler: ${err.message}` }, { status: 500 });
    }
  }
  // Also try to remove the directory (GitHub removes empty dirs automatically)

  // 2. Clean up Supabase
  await Promise.all([
    supabase.from('cms_content').delete().eq('page', id),
    supabase.from('cms_sections').delete().eq('page_id', id),
  ]);
  await supabase.from('cms_pages').delete().eq('id', id);

  return NextResponse.json({ ok: true });
}
